### ISSUE TITLE
If HSM loses connection for more than 5 minutes, returns CKR_SMS_ERROR even after connection is reestablish

### ISSUE THREAD

**Issue by vitorcabral94** [xipki/jpkcs11wrapper#3] opened 2024-01-16 14:33 UTC
Hi Lijun,

I'm currently using 2 HSM's: 1 Thales Luna and 1 Thales Protect Server in a project and they are both working perfectly with your library.

After doing some tests simulating network connection lost to check the behavior and see if it can recover after reestablish it, I found out that while not connected, we need to wait about 5 minutes for the following code to return the error  0x80000384 (CKR_SMS_ERROR).

https://github.com/xipki/jpkcs11wrapper/blob/332bbb511e5567116d286ef83e0ee2e9f18ad7c2/src/main/java/org/xipki/pkcs11/wrapper/PKCS11Module.java#L228

The error is fine and expected, but the problem comes after we connect the HSM to the network again, even if we start a new connection, the same error is returned in the code above and I can't get a new token until I restart the app that's using the HSM.

Tried to check if I could get some information about the C_GetInfo method but didn't found nothing relevant about what the method does internally.

I checked for both HSM's and they do the same thing, and even all the variables are equal between when everything is working fine or not, the only difference is the error in the code I linked.

Can you see if something can be done in the method to avoid this happening? With this behavior is impossible to build a proper health check because if the network connection is lost, nothing can be done. I can try to help you if needed, providing more information if necessary.

Best regards,
Vítor Cabral

**Comment by xipki** [comment] 2024-01-16 20:02
Hi Victor,

the error 0x80000834 indicates "General error from Secure Messaging System (SMS) – probably caused by HSM failure or network failure".  This is an error forwarded by the underlying PKCS11 library provided by HSM vendor. The library cannot handle the connection lost problem. Could you ask the HSM vendor for a solution?

In the application layer, what one can do is to create a new PKCS11Module, this however is impossible in jpkcss11wrapper, since it uses JDK's PKCS#11 wrapper, as stated here
https://github.com/xipki/jpkcs11wrapper/blob/332bbb511e5567116d286ef83e0ee2e9f18ad7c2/src/main/java/org/xipki/pkcs11/wrapper/PKCS11Module.java#L22-L26 .

If your application is able to create a new PKCS11Module, switch to use https://github.com/xipki/ipkcs11wrapper, no change in your code and configuration is needed.

BR
Lijun

**Comment by xipki** [comment] 2024-01-18 19:13
I found a discussion thread about similar problem. https://groups.google.com/g/pkcs11interop/c/bjKq6m7lk4Y
_ProtectServer Cryptoki Library in its default mode (NORMAL) doesn't know how to recover after connectivity problems, but the High Availability (HA) mode does. Check your ProtectServer documentation on activating the HA mode and you will get the library to recover from connectivity problems automatically after a given period of time (e.g. 1 minute)._

Could you try o use the `HA` mode?

**Comment by vitorcabral94** [comment] 2024-01-23 10:49
Hi Lijun,

Thank you for the tip about using HA mode. I will try testing with that mode and check if it works.

Thank you, best regards.

**Comment by vitorcabral94** [comment] 2024-02-02 14:57
Hi Lijun,

We already tested in HA mode and it's working better in returning connectivity, thanks for the tip!

Now I'm facing a different problem, my HSM is configured in FIPS mode, and with that I realized that I'm using CKM_RSA_PKCS mechanism for wrap and unwrap, which is not supported for wrap operations. I read the documentation and see that I can use the CKM_RSA_PKCS_OAEP mechanism, but in your code you throw an exception when we do mechanism.toCkMechanism(), and I didn't see any test in your code using this mechanism.

Can you give me some tip about using this mechanism?

Thanks you for all the help, best regards.

**Comment by xipki** [comment] 2024-02-02 17:03
The CKM_RSA_PKCS_OAEP is not supported by jpkcs11wrapper. Switch to https://github.com/xipki/ipkcs11wrapper, no change in your code and configuration is needed.

**Comment by vitorcabral94** [comment] 2024-02-05 11:19
I have all of my code developed for the jpkcs11wrapper, your saying I can switch to ijpcks11wrapper with no code changes? 

The unsupported OAEP mechanism is not the only problem I have, currently I can't connect to the Luna HSM HA slot via Keystore, the change of library will help me solve this issue too?

Sorry for all the questions, but I'm not fully understanding the difference between the two libraries and I'm afraid that, if I switch it, it will result in some issue related with code already developed with jpkcs11wrapper.

Best regards.

**Comment by xipki** [comment] 2024-02-05 21:14
> I have all of my code developed for the jpkcs11wrapper, your saying I can switch to ijpcks11wrapper with no code changes?

Yes. I implement both libraries (ipkcs11wrapper vs jpkcs11wrapper) explictly with the same package name, class name, and almost same method signatures.

> The unsupported OAEP mechanism is not the only problem I have, ...

OAEP prpblem will be resolved by using ipkcs11wrapper.

> ... currently I can't connect to the Luna HSM HA slot via Keystore, the change of library will help me solve this issue too?

Do you using the JDK's PKCS11 Provider? You need to analyse the detailed reason of the problem. ipkcs11wrapper does not resolve the problem, but it usually provide more accurate error information.

**Comment by vitorcabral94** [comment] 2024-02-06 10:19
> Do you using the JDK's PKCS11 Provider? You need to analyse the detailed reason of the problem. ipkcs11wrapper does not resolve the problem, but it usually provide more accurate error information.

To connect to Luna Keystore I'm using Luna Provider (from the HSM installation) for the Security Provider, and "Luna" in Keystore instance. I need to investigate it even more, because the only HSM I can't connect it's the one operating in FIPS mode and HA mode,  those modes doesn't influence the keystore connection? On "normal" Luna HSM's this connection is established just fine.

Thank you for all the help, I will check the ipkcs11wrapper and see if I can migrate easily. After the last question you can close the issue (or I can do it after your response)

**Comment by xipki** [comment] 2024-02-06 17:47
Sorry I cannot provide information about the Luna Provider. If you cannot access to the HSM via vendor's software, it shall also not work with other common software like the pkcs11wrapper. But I think this is other issue. Please raise a new issue for discussion, if needed.

**Closed by xipki** 2024-02-06 17:47 UTC
